### ISSUE TITLE
[Bug]: MySQL connection not working

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#16]
### What happened?

```
# Settings for Database or SQLite connection.
database:
  connection:
    # Settings for JDBC_HOST examples for connection:
    # MySQL: jdbc:mysql://your_host:port/name_of_database
    # SQLite: jdbc:sqlite:plugins/LiteEco/database.db
    #
    jbdc_host: jdbc:mysql://<>:3306/s12259_economy
    # User = username of user to connection your database.
    user: <>
    # Pass = password of user to connection your database.
    pass: <>
```

### Plugin Version

LiteEco-1.1.8-SNAPSHOT

### You detected problem on this server platform ?

PurpurMC 1.19.3-1892

### Relevant log output

https://paste.gg/p/ConaII_/046bfd571a124159afccbb04c3e147d0
