### ISSUE TITLE
[Feature Request]: Add admin-help section

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#21]
### Type of function to add or improvement

Others

### Your ideas

Example:
```yml
  help:
    - "<gray><st>─━━━━━━━━━━━━━━━━━─</st> <#64646F>[<#F9AD47>ECONOMIA<#64646F>]<gray> <st>─━━━━━━━━━━━━━━━━━─</st>"
    - " "
    - "  <gray>/money help"
    - " <white>-<#CFE7F0> Mostrar esta ayuda."
    - "  <gray>/money <yellow><usuario>"
    - " <white>-<#CFE7F0> Mostrar el saldo de una cuenta."
    - "  <gray>/money top <pink>[page]"
    - " <white>-<#CFE7F0> Mostrar jugadores mas ricos."
    - "  <gray>/money pay <yellow><usuario> <#3EE84D><amount>"
    - " <white>-<#CFE7F0> Transferir dinero a otro jugador."
    - " "
    - "<gray><st>─━━━━━━━━━━━━━━━━━─</st> <#64646F>[<#F9AD47>ECONOMIA<#64646F>] <gray><st>─━━━━━━━━━━━━━━━━━─</st>"
    - ""
  admin-help:
    - "<gray><st>─━━━━━━━━━━━━━━━━━─</st> <#64646F>[<#F9AD47>LiteEco<#64646F>] <gray><st>─━━━━━━━━━━━━━━━━━─</st>"
     - "<red>★ <gray>/money set <yellow><username> <#3EE84D><amount>"
    - " <white>-<#F39E9E> Establecer dinero de otro jugador."
    - "<red>★ <gray>/money add <yellow><username> <#3EE84D><amount>"
    - " <white>-<#F39E9E> Agregar dinero a otro jugador."
    - "<red>★ <gray>/money remove <yellow><username> <amount>"
    - " <white>-<#F39E9E> Quitar dinero a otro jugador."
    - "<red>★ <gray>/money lang [lang]"
    - " <white>-<#F39E9E> Cambiar de idioma."
    - "<red>★ <gray>/money reload"
    - " <white>-<#F39E9E> Recargar la configuracion."
    - "<gray><st>─━━━━━━━━━━━━━━━━━─</st> <#64646F>[<#F9AD47>LiteEco<#64646F>] <gray><st>─━━━━━━━━━━━━━━━━━─</st>"
    - ""
```
